### ISSUE TITLE
Missing font dir

### ISSUE THREAD

**Issue by rahulbhanushali** [pingcap/tidb-inspect-tools#45]
I followed the installation steps as described here: https://github.com/IzakMarais/reporter but for grafana_collector within this repo.

However, on running the grafana-collector command I get this error
main.go:81: [fatal] missing parameter: -font-dir

**Comment by LinuxGit** [comment]
We integrated it in tidb-ansible, see https://github.com/pingcap/tidb-ansible/blob/master/roles/grafana_collector/templates/run_grafana_collector_binary.sh.j2#L17.
